name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test script "install.all"
      run: sh 01-install.all.sh

    - name: Test script "personal.settings"
      run: sh 02-personal.settings